name: CD

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PUSH_TOKEN }}
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run production
    - name: Commit built assets
      run: |
        git config --local user.email "jeffrey92.hrb@gmail.com"
        git config --local user.name "jeffreyvanreenen"
        git checkout -B deploy
        git add -f public/
        git commit -m "Build front-end assets"
        git push -f origin deploy
    - name: Deploy to production
      uses: jeffreyvanreenen/digicate.nl@master
      with:
        username: root
        host: digicate.nl
        password: f53PDZ67!
        script: 'cd /var/www/html && ./server_deploy.sh'
